### ISSUE TITLE
debug_mesh pipeline validation error.

### ISSUE THREAD

**Issue by dorian-apanel-intel** [PacktPublishing/Mastering-Graphics-Programming-with-Vulkan#33] opened 2023-03-16 11:35 UTC
With core checks of validation layers, running Chapter 6 produces following error:

```
...
Parsing GPU Technique debug
temp.shader

temp.shader

UNASSIGNED-CoreValidation-Shader-InputNotProduced(ERROR / SPEC): msgNum: 602160055 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-InputNotProduced ] Object 0: handle = 0x5131e00000000419, name = debug_mesh, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x23e43bb7 | Vertex shader consumes input at location 0 but not provided
    Objects: 1
       [0]  0x5131e00000000419, type: 15, name: debug_mesh
A breakpoint instruction (__debugbreak() statement or a similar call) was executed in RaptorEngine_Chapter6_Debug.exe.
```

**Comment by theWatchmen** [comment] 2023-09-08 09:48
Better late than never :D Turns out we did some refactoring for the pipeline definition and missed a couple of files. This should now be fixed.

**Comment by theWatchmen** [comment] 2023-10-20 18:45
Closing this for now, feel free to reopen if the issue is not fixed.

**Closed by theWatchmen** 2023-10-20 18:45 UTC
